name: Check Backend Changes
description: Checks for changes to backend (python) files
outputs:
  files-changed:
    description: 'Whether backend (python) files were changed'
    value: ${{ steps.changed-files.outputs.python_any_changed }}
runs:
  using: 'composite'
  steps:
    - name: Check for changed python files
      id: changed-files
      uses: tj-actions/changed-files@v40
      with:
        files_yaml: |
          python:
            - 'pyproject.toml'
            - 'invokeai/**'
            - '!invokeai/frontend/web/**'
            - 'tests/**'
