name: invokeai
channels:
  - pytorch
  - defaults
dependencies:
  - python>=3.9
  - cudatoolkit
  - pytorch
  - torchvision
  - numpy
  - pip:
    - albumentations
    - opencv-python
    - pudb
    - imageio
    - imageio-ffmpeg
    - pytorch-lightning
    - omegaconf
    - realesrgan
    - test-tube>
    - streamlit
    - send2trash
    - pillow
    - einops
    - pyreadline3
    - torch-fidelity
    - transformers
    - torchmetrics
    - flask
    - flask_socketio
    - flask_cors
    - dependency_injector
    - eventlet
    - kornia
    - -e git+https://github.com/openai/CLIP.git@main#egg
    - -e git+https://github.com/CompVis/taming-transformers.git@master#egg
    - -e git+https://github.com/Birch-san/k-diffusion.git@mps#egg
    - -e git+https://github.com/TencentARC/GFPGAN.git#egg
    - -e .
