name: Test invoke.py pip

# This is a dummy stand-in for the actual tests
# we don't need to run python tests on non-Python changes
# But PRs require passing tests to be mergeable

on:
  pull_request:
    paths:
      - '**'
      - '!pyproject.toml'
      - '!invokeai/**'
      - '!tests/**'
      - 'invokeai/frontend/web/**'
  merge_group:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  matrix:
    if: github.event.pull_request.draft == false
    strategy:
      matrix:
        python-version:
          - '3.10'
        pytorch:
          - linux-cuda-11_7
          - linux-rocm-5_2
          - linux-cpu
          - macos-default
          - windows-cpu
        include:
          - pytorch: linux-cuda-11_7
            os: ubuntu-22.04
          - pytorch: linux-rocm-5_2
            os: ubuntu-22.04
          - pytorch: linux-cpu
            os: ubuntu-22.04
          - pytorch: macos-default
            os: macOS-12
          - pytorch: windows-cpu
            os: windows-2022
    name: ${{ matrix.pytorch }} on ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: skip
        run: echo "no build required"
